### ISSUE TITLE
DropShadow filter change options to include xDistance and yDistance

### ISSUE THREAD

**Issue by KennethGomez** [pixijs/filters#256]
I think that instead of having a variable that includes both x-axis distance and y-axis distance it'd be better to split them up because you don't always want a diagonal **-XY/+XY** shadow.

That way this filter would be much more flexible and likely a better one.

**Comment by bigtimebuddy** [comment]
I agree `rotation` and `distance` are not that intuitive to use for setting the shadow. And offset is better.
