### ISSUE TITLE
demo site doesn't work

### ISSUE THREAD

**Issue by rizen** [pixijs/filters#292]
Various pages link to https://pixijs.io/pixi-filters/tools/demo/ as a demo, but it returns a 404 error.

**Comment by bigtimebuddy** [comment]
Please use https://pixijs.io/filters/tools/demo/

**Comment by rizen** [comment]
Cool, thanks! The specific pages that have the wrong links are:

https://filters.pixijs.download/main/docs/index.html

and 

https://github.com/pixijs/filters

**Comment by bigtimebuddy** [comment]
Cool, thanks for letting me know. I fixed this in the readme 6992dcf which will be updated in those places
