### ISSUE TITLE
avoid blurring text with filters?

### ISSUE THREAD

**Issue by andrewljohnson** [pixijs/filters#298]
I was able to get my text to display sharply using pixi, except when I apply filters. This example uses an AdjustmentFilter, but I found it true with all filters I tried (godray, dropshadow, others). 

Here are two cards. The darker card is only different in that it has an AdjustmentFilter applied.

![image](https://user-images.githubusercontent.com/455551/117482296-05b93880-af19-11eb-996d-d8f0d3a48597.png)

My app settings are like this:

    this.app = new PIXI.Application({
        width: appWidth, 
        height: appHeight, 
        antialias: false, 
        backgroundAlpha: true,
        resolution: window.devicePixelRatio || 1,
        autoDensity: true
     });

The cards sprite and text are created like this:

    let cardSprite = new PIXI.Sprite.from(cardTexture);
    cardSprite.interactive = true;
    cardSprite.anchor.set(.5);
    cardSprite.buttonMode = true;
    let options = {fontFamily : 'Helvetica', fontSize: 8, fill : 0x00000, wordWrap: true, wordWrapWidth: 56};
    let name = new PIXI.Text(card.name, options);
    cardSprite.addChild(name);

The filter is added like this:

    cardSprite.filters = [new PIXI.filters.AdjustmentFilter({ brightness: .8,}),];

**Comment by bigtimebuddy** [comment]
Try setting the global filters resolution  defaultto be the same as your renderer resolution:

```js
PIXI.settings.FILTER_RESOLUTION = window.devicePixelRatio || 1;
```
Alternatively, set it on a per-filter basis.
```js
const filter = new PIXI.filters.AdjustmentFilter({ brightness: .8,});
filter.resolution = window.devicePixelRatio || 1;
cardSprite.filters = [filter]; 
```

**Comment by bigtimebuddy** [comment]
Also, for support questions, if you wouldn't mind making a Discussion thread instead of an Issue, that's be :+1:. We'd like to keep issues for specific library bugs.
