### ISSUE TITLE
GlitchFilter Broken in PixiJS 5 & 6

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/filters#299]
Visible in demo, but here's a reproduction:
https://jsfiddle.net/bigtimebuddy/cxq14shr/

Slices no longer are visible, only the channel offsets.

Here's how it's suppose to look: (PixiJS v4 and Filters v2)
https://jsfiddle.net/bigtimebuddy/s7vjgm36/

cc @miltoncandelero

**Comment by bigtimebuddy** [comment]
Merged and released

**Comment by bigtimebuddy** [comment]
@miltoncandelero Feel free to [invoice PixiJS](https://opencollective.com/pixijs) for the bounty on the bug if you'd like. Please make sure to include a link to this issue.

**Comment by miltoncandelero** [comment]
I didn't do it for the bounty and even if I did I wouldn't be able to collect it due to the tax laws of Argentina.

nevertheless, I appreciate the intent
