### ISSUE TITLE
changing DropShadowFilter.defaults

### ISSUE THREAD

**Issue by human211** [pixijs/filters#302]
Hi!
When i create a new DropShadow filter without parameters it differs from the default.
I found this code...here default values are overridden. Is it correct?
https://github.com/pixijs/filters/blob/b64ddd949b4d2ee864ab96ce4daa6a549b786064/filters/drop-shadow/src/DropShadowFilter.ts#L80

**Comment by ivanpopelyshev** [comment]
Lol! Make a PR.
