### ISSUE TITLE
Ascii Filter looks better on orignal Shadertoy

### ISSUE THREAD

**Issue by benoitwimart** [pixijs/filters#325]
Hi,

When I zoom to this Ascii Filter (used by pxijs)
https://www.shadertoy.com/view/lssGDj
the '&' is really better than the filter demo : https://filters.pixijs.download/main/demo/index.html
Maybe it's upside down ?¿

**Comment by movAX13h** [comment]
You're right. Someone should adapt the changes made to the shader (see update note at the top of shader code) here in the repo version.
