### ISSUE TITLE
DropShadowFilter does not blur properly 

### ISSUE THREAD

**Issue by JoeriTheGreat** [pixijs/filters#329]
I want to create a nice dropdown shadow like this 
![image](https://user-images.githubusercontent.com/37139936/165273950-9909469a-216b-4062-b507-028e1314b954.png)

But the shadow has what it seems a bounding box and does not blur out properly.
Is there a way to overcome this issue ?

https://jsfiddle.net/joerithegreat/3qoke6jn/

**Comment by bigtimebuddy** [comment]
Try manually adding `padding`: https://jsfiddle.net/3m7tekqc/

I think the [_updatePadding](https://github.com/pixijs/filters/blob/main/filters/drop-shadow/src/DropShadowFilter.ts#L127-L130) function in the filter isn't considering the `quality` which has an effect, but manually setting the padding should override.

**Comment by bigtimebuddy** [comment]
@JoeriTheGreat for general support, please consider opening a [discussion](https://github.com/pixijs/pixijs/discussions) describing what you're trying to achieve. I'm going to close this issue since the initial query has been addressed.
