### ISSUE TITLE
I used colorMapFilter to map the LUT image, but the effect was just to mask the original image

### ISSUE THREAD

**Issue by pzppzz** [pixijs/filters#343]
Sometimes I get this effect, which is exactly what I want.
![image](https://user-images.githubusercontent.com/89590352/187928324-78b1b383-8224-45b4-a241-97d2f3e8625e.png)
But sometimes you get this effect.
![image](https://user-images.githubusercontent.com/89590352/187929528-b3ac7ae8-8882-4d82-94d3-5d2b54990ed7.png)
This is the original image. The above two cases are the same colorMap.
![image](https://user-images.githubusercontent.com/89590352/187930000-5712fb6e-445c-490b-82d3-bb6d310d4b74.png)

**Comment by bigtimebuddy** [comment]
Please provide more details, example. This issue is insufficient.

**Comment by pzppzz** [comment]
I think I made a mistake. But I'm curious how does the width and height of the first parameter to colorMatrixFilter affect the color mapping

**Comment by pzppzz** [comment]
> Please provide more details, example. This issue is insufficient.
Is that enough description now?

**Comment by bigtimebuddy** [comment]
Are you reporting a bug or do you need help? I don't understand your issue.

It's always useful to provide a running example, so that it's easier to diagnose your issue. What does the LUT look like that you're using?

**Comment by bigtimebuddy** [comment]
Are you sure you have completely loaded the LUT before applying this? This seems like a race-condition where the image isn't fully loaded and the height is only getting maybe a value of 1, which would the the first blue pixel. That could create some issues for sure.

https://github.com/pixijs/filters/blob/73ca99b27515244ffdb321ca40f780a114b7c26c/filters/color-map/src/ColorMapFilter.ts#L92

**Comment by pzppzz** [comment]
> Are you sure you have completely loaded the LUT before applying this? This seems like a race-condition where the image isn't fully loaded and the height is only getting maybe a value of 1, which would the the first blue pixel. That could create some issues for sure.
> 
> https://github.com/pixijs/filters/blob/73ca99b27515244ffdb321ca40f780a114b7c26c/filters/color-map/src/ColorMapFilter.ts#L92

Thank you very much. My problem is solved.
