### ISSUE TITLE
Pixi v6 + Vue 3 (Vite) has error on import

### ISSUE THREAD

**Issue by evdevru** [pixijs/filters#346]
Im using vue 3 with default config and cant import filter. Can you help me ?

    import filters from "pixi-filters";
Error: Build failed with 26 errors:

No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "settings"
No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "DEG_TO_RAD"
No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "utils"
No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "Point"

    node_modules/@pixi/filter-kawase-blur/dist/filter-kawase-blur.mjs:7:22:
      7 │  */import{Filter as m,Point as h}from"@pixi/core";var c=`attribute vec2 aVertexPosition;`

**Comment by fyyyyy** [comment]
change first line in node_modules/@pixi/filter-outline/dist/filter-outline.mjs to 
` */import { Filter as l, utils as i } from "pixi.js"`
