### ISSUE TITLE
Pixi core 7.0.0 dependancy

### ISSUE THREAD

**Issue by petem24** [pixijs/filters#347]
Pixi filters is dependant on pixi core v7 which is still in beta. Throws peer dependancy error for anymore on latest stable version of pixi. I think filters v5.0 should prerelease?

`npm WARN While resolving: @pixi/filter-drop-shadow@5.0.0
npm WARN Found: @pixi/core@6.5.6
npm WARN node_modules/@pixi/core
npm WARN   peer @pixi/core@"6.5.6" from @pixi/accessibility@6.5.6
npm WARN   node_modules/@pixi/accessibility
npm WARN     @pixi/accessibility@"6.5.6" from pixi.js@6.5.6
npm WARN     node_modules/pixi.js
npm WARN   25 more (@pixi/app, @pixi/compressed-textures, @pixi/extract, ...)
npm WARN `

`npm WARN Conflicting peer dependency: @pixi/core@7.0.0-beta.3
npm WARN node_modules/@pixi/core
npm WARN   peer @pixi/core@"^7.0.0-X" from @pixi/filter-kawase-blur@5.0.0
npm WARN   node_modules/@pixi/filter-kawase-blur
npm WARN     @pixi/filter-kawase-blur@"5.0.0" from @pixi/filter-drop-shadow@5.0.0
npm WARN     node_modules/@pixi/filter-drop-shadow`

**Comment by bigtimebuddy** [comment]
Hello! You should keep filters on v4 for compatibility with PixiJS v6. Only use v5 if you are transitioning to the PixiJS v7 prerelease.

**Comment by petem24** [comment]
Got it working with `"@pixi/filter-drop-shadow": "4.2.0"`
