### ISSUE TITLE
Get error trying to use CRTFilter

### ISSUE THREAD

**Issue by trevorwrightdev** [pixijs/filters#379]
I get this error when trying to apply the CRTFilter.
```
Uncaught TypeError: Class constructor vi cannot be invoked without 'new'
    at new n (CRTFilter.ts:72:9)
    at app.js:65:22
```
I'm using vanilla JS, so I could be applying it wrong. Here is all I am doing:
```
app.stage.filters = [new PIXI.filters.CRTFilter()]
```
Can someone tell me how to do this in vanilla JS?

**Comment by thurinus** [comment]
I just ran into this, and got it to work by using the browser distribution:
```
https://cdn.jsdelivr.net/npm/pixi-filters@latest/dist/browser/pixi-filters.min.js
```
I assume you used the README's recommendation of 
```
https://cdn.jsdelivr.net/npm/pixi-filters@latest/dist/pixi-filters.js
```
