### ISSUE TITLE
`DropShadowFilter`'s `offset` doesn't respect target scale

### ISSUE THREAD

**Issue by zumm** [pixijs/filters#386]
`offset` always stays same regardless of target's scale. It makes impossible to scale objects affected by `DropShadowFilter`.

**Comment by fybits** [comment]
Same issue here. I have a parent that is scaling. And I have to update drop shadow's offet every frame manually.

**Comment by bigtimebuddy** [comment]
Unfortunately, we cannot support scaling the offset based on the world scale of the display object. You'll need to manage this yourself by updating the offset property.
