### ISSUE TITLE
Deprecation Warning: `utils.hex2rgb` when using PixiJS filters with PixiJS v7.2.0+

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/filters#387]
PixiJS filters are using deprecated utils functions like `hex2rgb`, which prints deprecation warnings into the console:

```
PixiJS Deprecation Warning: utils.hex2rgb is deprecated, use Color#toRgbArray instead
Deprecated since v7.2.0
```

It wouls be nice to see an updated version of PixiJS filters without these warnings 🙂

**Comment by bigtimebuddy** [comment]
Yeah, something that uses Color. These filters need updating

**Comment by FloodGames** [comment]
This whole package needs some love?
npm install
```

Build all filters, demo and screenshots by running the following:

Can't even get past. 
"npm run build" after "npm install" 

```
npm ERR! code 1
npm ERR! path C:\GIT\filters\node_modules\canvas
npm ERR! command failed
```

I would be interested in trying to update some packages without breaking everything, if I get it up and running.

**Comment by FloodGames** [comment]
I'm trying https://github.com/pixijs/filters/pull/389

**Comment by bigtimebuddy** [comment]
This project will not be updating v7 deprecations, closing for now.
