### ISSUE TITLE
a polar filter

### ISSUE THREAD

**Issue by lzy100p** [pixijs/filters#393]
Dear colinsullivan, I would like to ask you if you could develop a polar coordinates filter that would be of great benefit to me. I understand that this will require an investment of time and effort on your part, but I would appreciate it if you could do so at your convenience.
This filter converts Cartesian coordinates in an image to polar coordinates and applies a certain distortion to achieve interesting visual effects.

thanks

a polar coordinates in ps:
https://helpx.adobe.com/photoshop/how-to/use-polar-coordinates-filter.html

![use-polar-coordinates-filter_5 jpg img](https://github.com/pixijs/filters/assets/6929602/5877c9bd-a5ff-4097-8650-86e6bddf055b)

**Comment by bigtimebuddy** [comment]
This project is a series of community-supported filters. If someone would like a similar effect, please consider contributing an effect. Closing this request.
