### ISSUE TITLE
demo site not working

### ISSUE THREAD

**Issue by declann** [pixijs/filters#407]
https://pixijs.io/filters/docs/

links to:

https://pixijs.io/filters/demo/ which gives a 404

and individual demos link to:

https://filters.pixijs.download/main/demo/index.html?enabled=AdjustmentFilter

which is giving access denied responses

**Comment by bigtimebuddy** [comment]
We are working on supporting v8 and moving stuff around, atm. This is a known issue until we make a release. Links on the Readme have been updated.

**Comment by bigtimebuddy** [comment]
Fixed
