### ISSUE TITLE
Deprecation Warning in Drop Shadow Filter

### ISSUE THREAD

**Issue by coeing** [pixijs/filters#411]
```
PixiJS Deprecation Warning: settings.FILTER_RESOLUTION is deprecated, use Filter.defaultResolutionDeprecated since v7.1.0
```

Using `@pixi/filter-drop-shadow@5.2.0` with `pixi.js@7.3.3`

The line responsible for this should be this one: https://github.com/pixijs/filters/blob/b013c9bd8169a0c7c96bf08b5122f5e8b4bc2c8a/filters/drop-shadow/src/DropShadowFilter.ts#L46C9-L46C47

**Comment by bigtimebuddy** [comment]
This project will not be fixing v7 deprecation warnings. Issues have been addressed in PixiJS v8.
