### ISSUE TITLE
Get the bitmap data of a display object with a filter applied

### ISSUE THREAD

**Issue by velara3** [pixijs/filters#445]
I went through the examples section and I didn't see an example of adding an image to the stage, adding a filter to it and then getting the transparent bitmap data of the image for a PNG. I only see [jpeg and webp](https://pixijs.download/release/docs/PIXI.CanvasExtract.html). 

Well, I found the screenshot [example](https://codesandbox.io/p/sandbox/ecstatic-dew-ffmc86?file=%2Fsrc%2Findex.js%3A10%2C1-11%2C1&utm_medium=sandpack) so I'll work on that but that doesn't show how to get the image data with filters applied unless it adds it by default. 

Related questions: 

1. Is there a forum or chat room or can we ask questions like this here? Is there support on StackOverflow? 
2. Can we create our own filters or modify the existing filters? 
3. Will this run in nodejs? 

Also, on [this](https://pixijs.download/release/docs/index.html) page the link to the filter examples is down: 
Points to [here](https://pixijs.io/filters/tools/demo/).

**Comment by bigtimebuddy** [comment]
Extract also supports image/png as well. That is, in fact, the default.

You can join the PixiJS Discord. There's a link on the website and it's very active.

You can add your own filters or modify these to suit your needs. It's open source after all!

Lastly, there's a package called `@pixi/node` (github.com/pixijs/node) that you can use to render filters in Node.js without a browser.
