### ISSUE TITLE
Pixi filters don't work on OffscreenCanvas

### ISSUE THREAD

**Issue by gnut-neygun** [pixijs/filters#463]
Reproduce:
- Use the TwistFilter on an OffscreenCanvas with Pixi

Details:

The class TiltShiftAxisFilter is accessing the window object to get the innerHeight and innerWidth, which doesn't exist on a worker thread, thus exception.

**Comment by ucarno** [comment]
I also experience the same issue with BevelFilter (which does not access window object itself) in webworker. My temporary fix was to just copy BevelFilter into my project and use that instead of the original.

**Comment by xeoshow** [comment]
Hello @ucarno ,

Do you mean below filter? Which pixijs version and filters version are you using? I also tried the same in the webworker, but got error telling that "ReferenceError: document is not defined", could you please kindly help? Thanks.
https://github.com/pixijs/filters/blob/main/src/bevel/BevelFilter.ts
