### ISSUE TITLE
Adjustment Filter not working in pixi v8

### ISSUE THREAD

**Issue by steven-twerdochlib** [pixijs/filters#466]
Hi,
I'm currently upgrading to pixi v8 from v7 and my Adjustment Filter is not working although I can see the correct filters in the container.filters (I used console.log() to check). 
Has there been some changes to make it work with v8? I see there's v6 release on github of @pixi/filter-adjustment library but this isn't available on npm store [](https://www.npmjs.com/package/@pixi/filter-adjustment ), could this be why it's failing in pixi v8? 
Note: npm store only goes up to v5.1.1

Image of filters added correctly:
![image](https://github.com/user-attachments/assets/8c3da371-cbae-4a96-9291-8856f6b4df16)

**Comment by bigtimebuddy** [comment]
You'll want to download the latest `pixi-filters` package. Then you can import `pixi-filters/adjustment` instead of `@pixi/filter-adjustment`

**Comment by steven-twerdochlib** [comment]
> You'll want to download the latest `pixi-filters` package. Then you can import `pixi-filters/adjustment` instead of `@pixi/filter-adjustment`

Thanks, this worked. I think this should really be mentioned in v8 migration guide as it's not obvious there's a new pixi package for v8 instead of a new release of original @pixi/filter-adjustment. Just my opinion though.

**Comment by bigtimebuddy** [comment]
Do you mean this guide? https://pixijs.com/8.x/guides/migrations/v8

**Comment by steven-twerdochlib** [comment]
> Do you mean this guide? https://pixijs.com/8.x/guides/migrations/v8

Yh that's the one
