### ISSUE TITLE
How to use non-builtin v8 filters?

### ISSUE THREAD

**Issue by GreenArrow18** [pixijs/filters#478]
Using PixiJS v8. My package.json dependencies:

> "pixi-filters": "6.0.5"
> "pixi.js": "8.6.3"
> 

This works:
```
import { ColorMatrixFilter } from 'pixi.js';
const filter = new ColorMatrixFilter();
```

I can't figure out how to use the non-builtin filters though.
```
import { BloomFilter } from 'pixi-filters';
const filter = new BloomFilter();

OR

import { BloomFilter } from 'pixi-filters/bloom';
const filter = new BloomFilter();
```

I am getting a typescript error there: _Unsafe assignment of an error typed value._

Can you provide some basic examples that work with v8? Thanks.

**Comment by bigtimebuddy** [comment]
I wasn't able to reproduce this. I did this:

```
npm create pixi.js@latest

✔ Project name: … pixi-project
✔ Select a type of template: › Bundler Templates
✔ Select a variant: › Vite

cd pixi-project 
npm install
npm install pixi-filters
npm run dev
```

Modify **src/main.ts**:

```ts
import { BloomFilter } from "pixi-filters";

// ...

bunny.filters = [new BloomFilter()];
```

**Comment by GreenArrow18** [comment]
Your sample works!

My code still wasn't working, but strangely enough, a restart of VS Code fixed everything without changes.

So sorry for the bother, and thanks for taking the time to test.
